### ISSUE TITLE
Logging system

### ISSUE THREAD

**Issue by FluffyMoses** [FluffyMoses/BeReSo#22]
- log all actions in new database table bereso_log
- default disabled

**Comment by youssefoukh** [comment]
Hello i would suggest you use triggers to implement this functionnality 
check out this answer for further explanation https://stackoverflow.com/a/12657012

**Comment by FluffyMoses** [comment]
added with version 3.6 - commit 3c69b0f

after enabling via user_log = 1 - just the user triggered changes are logged not all queries to keep it as "clear" as possible (still much logging entries with a few users
